#YAML File to Build the image from Source code,push the Docker Image to Artifactory Repository and Deploy to GCP Cloud Run.
name: Build and Deploy to Cloud Run
on:
  push:
    branches: [ "main" ]
#Environment Variables
env:
  PROJECT_ID: driven-park-410307                                     #Google Cloud project id
  GAR_LOCATION: us-central1-docker.pkg.dev/driven-park-410307/hello  #Artifact Registry location
  REPOSITORY: hello                                                  #Artifact Registry repository name
  SERVICE: hello                                                     #Cloud Run service name
  REGION: us-central1                                                #Region Name, where Cloud Run service needs to be deployed.
jobs:
  deploy:
  
    # Add 'id-token' with the intended permissions for workload identity federation
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # NOTE: Alternative option - authentication via credentials json
      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v2'
        with:
           credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      # BEGIN - Docker auth and build (NOTE: If you already have a container image, these Docker steps can be omitted)

      # Authenticate Docker to Google Cloud Artifact Registry
      - name: Configure docker for GCP
        run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

      - name: Build and Push Container
        run: |-
          docker build -t "${{ env.GAR_LOCATION }}/${{ env.SERVICE }}:${{ github.sha }}" ./
          docker push "${{ env.GAR_LOCATION }}/${{ env.SERVICE }}:${{ github.sha }}"

      # END - Docker auth and build
      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ env.SERVICE }}
          region: ${{ env.REGION }}
          # NOTE: If using a pre-built image, update the image name here
          image: ${{ env.GAR_LOCATION }}/${{ env.SERVICE }}:${{ github.sha }}
          allow-unauthenticated: true

      # If required, use the Cloud Run url output in later steps
      - name: Show Output
        run: echo ${{ steps.deploy.outputs.url }}
